steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: '/opt/sap/mta.jar'
  neoDeploy:
    neo:
      credentialsId: 'NEO_DEPLOY'
      account: 'vnpnmamw7d'
      host: 'eu2.hana.ondemand.com'